### ISSUE TITLE
`--substitute` needs to 

### ISSUE THREAD

**Issue by rocallahan** [Pernosco/pernosco-submit#10]
https://github.com/Pernosco/pernosco-submit/pull/7 passes `--substitute` arguments through to `rr sources`. It overrides the `DW_AT_comp_dir` for a specific binary. So, if the sources for that binary were built in compilation working directory A but now that filesystem subtree is in directory B, we can force rr sources to look in directory B, finding the files.

The problem is that the file paths output by rr sources contain directory B, and `pernosco-submit` packages sources into `sources.zip` and `sources.user` with names containing B. Pernosco sees directory A in the debuginfo, but the files aren't there.

@db48x I don't know how this worked for you...

**Comment by rocallahan** [comment]
One way to fix this would be for `rr sources` to emit a record (A, B) for every directory A that was substituted with B. Then `pernosco-submit` could convert those into links from A to B.

This would work for many cases but I don't think it would for the cases where LLVM has helpfully emitted `.` for the `DW_AT_comp_dir`.

**Comment by rocallahan** [comment]
We probably need to emit the substitutions themselves as (binary name, directory) records into the sources.* files and extend our source file logic to include them.

**Comment by rocallahan** [comment]
Fixed in a84674e989fbeff97f92547f3216622675bc7eda

**Comment by db48x** [comment]
I haven't had time to look back at my older Pernosco uploads, but I recall figuring that this would work because GDB searches not just for the whole path of the source file, but also just the filename. On the other hand, I don't actually know if Pernosco is relying on GDB for that or not.

**Comment by rocallahan** [comment]
Thanks. We aren't using gdb for that.
