### ISSUE TITLE
The current master requires a very recent python

### ISSUE THREAD

**Issue by fqueze** [Pernosco/pernosco-submit#12]
The code in https://github.com/Pernosco/pernosco-submit/commit/6638afc077303991bab1720c363ae1fbdeec2697 doesn't work with the python3 version (3.6.9) that comes with `#!/usr/bin/env python3` on my Ubuntu 18.04 lts installation.

It seems ` from __future__ import annotations` requires python 3.7, `TypedDict` in the `typing` module (for this line: ` from typing import Optional, List, IO, Union, Any, Mapping, Tuple, Dict, cast, NewType, TypedDict`) requires python 3.8.

And after updating to 3.8, which is the newest version available on this ubuntu, the line `StrPath = Union[str, os.PathLike[str]]` (line 9 in pernoscoshared/base.py) fails with a "TypeError: 'ABCMeta' object is not subscriptable" error. A random comment I found while searching for this python error seems to indicate the behavior of this has changed on python 3.9.

Reverting to the previous commit seems to work for me.

**Comment by rocallahan** [comment]
This is sad.

I've pushed changes to make the script work with Python 3.8 (working around that ABCMeta error), and to bail out if run with Python older than 3.8.

I hope we can get away with requiring 3.8 given Ubuntu 18 LTS packages it. Apparently there is even a PPA for Ubuntu 16.

**Comment by fqueze** [comment]
> I've pushed changes to make the script work with Python 3.8 (working around that ABCMeta error), and to bail out if run with Python older than 3.8.

Thanks for the quick reaction on this!

Did you mean to put your check before the `from __future__ import annotations` line which requires python 3.7?

**Comment by rocallahan** [comment]
`from __future__ import annotations` has to go first unfortunately.

I guess we could work around that by putting the main script into a module which is imported by a wrapper that doesn't use `from __future__ import annotations` but I'd rather not...
