### ISSUE TITLE
could upload be less noisy?

### ISSUE THREAD

**Issue by skobes-chromium** [Pernosco/pernosco-submit#18]
`pernosco-submit upload` writes a lot of output to the console. It looks like a JSON blob for every .dwo file of which there are thousands(?). It's kind of annoying because I lose the scrollback for previous commands.

It would be great if most of the output was suppressed by default, maybe with a `--verbose` option for when it is needed.

**Comment by khuey** [comment]
Can you paste a sample?

**Comment by skobes-chromium** [comment]
Here is the last ~500K or so of output (due to pastebin limit)

https://pastebin.com/raw/NLE2kfSt

**Comment by khuey** [comment]
I believe c948420fb3becb28843c67726ac9bdcfc801c852 will fix this.
