### ISSUE TITLE
Getting "CPU feature AVX512 enabled when recording trace, but …" even after disabling it

### ISSUE THREAD

**Issue by simon-friedberger** [Pernosco/pernosco-submit#20]
I've disabled it on my Ryzen 9 7900X using `clearcpuid=304 no5lvl` and `/proc/cpuinfo` is not showing avx512 anymore but I am still getting the warning. Yes, I am submitting a trace that was created after disabling it.

**Comment by khuey** [comment]
Thanks for reporting!
