### ISSUE TITLE
Consider requiring at least one source-path unless an argument explicitly waives the requirement

### ISSUE THREAD

**Issue by asutherland** [Pernosco/pernosco-submit#8]
I've been provided with multiple traces submitted by multiple people via pernosco-submit that have no source available and I don't believe it was ever their intent to avoid including sources.  I think it's great that the default of pernosco-submit is privacy-centric to only consider (source) directory trees that are explicitly listed, but given that it's always desirable to have source available for a debugging tool, I'd suggest it might be appropriate to print out a large error if no (valid) source roots are provided unless an argument explicitly indicates that the caller intentionally did not include a source directory.

If backwards compat is a concern, perhaps the script can explicitly check the PERNOSCO_GROUP and do this only for `mozilla` and I can get the relevant parties to agree to this?

Motivating context by related bug:  When trying to do things like use `$tid` as a "print" for "Executions of" without source, it seems like the query ends up failing for some reason.  When this is fixed it'd still be nice to make it more clear to people when they are forgetting to submit source.

**Comment by khuey** [comment]
That sounds like a good idea.

Can you give me some STR for the latter issue with `$tid`?

**Comment by asutherland** [comment]
(Handling the STR on chat.mozilla.org.)

**Comment by rocallahan** [comment]
You might record something where all the sources you care about are in public repos already, in which case no listed directories is fine. But I agree doing as you suggest is a good idea.

**Comment by khuey** [comment]
There's no a `--no-local-sources` option and providing zero paths without that flag will error out.
